### ISSUE TITLE
osmesa backend

### ISSUE THREAD

**Issue by christopherhesse** [moderngl/glcontext#10]
The standalone EGL backend looks great for hardware-accelerated 3D rendering on headless Linux servers.  For software rendering, it could be useful to have an [osmesa](https://www.mesa3d.org/osmesa.html) backend which allows software rendering without an X server running.

Admittedly, headless software rendering from python isn't the most popular setup, but is useful for things like reinforcement learning environments such as https://gym.openai.com/envs/CarRacing-v0/ where you want to render pixels, but often on a remote linux machine, and sometimes without a GPU available (on that machine).

For reference, here's glfw's osmesa context: https://github.com/glfw/glfw/blob/master/src/osmesa_context.c

How do you guys feel about an osmesa backend?

**Comment by einarf** [comment]
I guess the general attitude is: If it can be supported, we're all for it. As long as it can support at least opengl 3.3 contexts it should in theory work out of the box for moderngl 5.6.

Still we're constrained be the fact that a day only has 24 hours, so contributions are extremely appreciated.

**Comment by christopherhesse** [comment]
Seems like with the correct setup, EGL can do headless rendering through mesa, so going to close this for now.
