### ISSUE TITLE
Python39 manylinux wheels are missing

### ISSUE THREAD

**Issue by naveen521kk** [moderngl/glcontext#17]
Someone reported that when installing [Manim](https://github.com/manimcommunity/manim), they were compiling `glcontext` and they failed to because they were missing some headers, their config was Python 3.9.2 on amd64, QubesOS like `Debian 11 testing`, and  I could see https://pypi.org/project/glcontext/#files that manylinux wheels for `py39` are missing.

**Comment by einarf** [comment]
Will look into this. Might just build it manually for now. Need to move over to github actions soon.

**Comment by FrankFirsching** [comment]
Any news on this? Seems you started on the GitHub actions, but are they done? I'm having the same Python3.9 issues for my project, that utilizes ModernGL inside a blender add-on (https://github.com/FrankFirsching/PAINTicle).
(btw. ModernGL is really a great python module, thanks for providing this to the open source world!)

**Comment by einarf** [comment]
We released a new version in PyPI now. No missing wheels this time.
