### ISSUE TITLE
Wayland / EGL

### ISSUE THREAD

**Issue by einarf** [moderngl/glcontext#18]
Might need to start thinking about Wayland. The backend should use EGL instead of X11.

`XDG_SESSION_TYPE` env var should™ contain "x11" or "wayland" making us able to select the right backend for linux.

**Comment by einarf** [comment]
We do take PRs 😄

**Comment by szabolcsdombi** [comment]
there is some code for egl [egl.cpp](https://github.com/moderngl/glcontext/blob/master/glcontext/egl.cpp)
I probably did not test it. I never had both EGL + OpenGL 3.3+ on my computer running.

**Comment by einarf** [comment]
The EGL backend works great. It also support device id so it can use multiple gpus. However, the backend is only for headless so I guess it could be tweaked with a "detect" more.

**Comment by alexyz79** [comment]
Hi, I have created a [pull request](https://github.com/moderngl/glcontext/pull/30) with a shared context for the EGL backend, I have tested it on Fedora 36 with wayland a it's working,

**Comment by szabolcsdombi** [comment]
pr looks good, merged, we will make a release with it.
