### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by bhomerTk** [moderngl/glcontext#26]
Is there any example code showing how to use your glcontext package?  I am unsure how to extend ctx.load ('glViewport') shown in your test.py file.  How would I later invoke the glViewport () command?  Do I have to preload all the opengl commands?

**Comment by szabolcsdombi** [comment]
there are two libraries actively using `glcontext`
none of those use the returned functions from pure python as it is a no goal for this library.
the returned function pointers are for C/C++ code. (raw function pointers are returned as they would be returned from C/C++ with dlsym, GetProcAddress or _glGetProcAddress)

to get pure python compatible function pointers please use PyOpenGL or similar.

The content of this library was entirely in moderngl before version 5.6.0. the sole purpose of moving the OpenGL function loading into a separate library was to let developers easily extend or entirely replace the function loading.

One can use moderngl without glcontext by mocking the glcontext api.
If you have a native application in C++ but the rendering code uses python + moderngl you might want to implement your own window, OpenGL context and function loading.

The other library using `glcontext` as the default OpenGL context provider and gl function loader is [`zengl`](https://github.com/szabolcsdombi/zengl). It is a quite new approach implementing a subset of moderngl in a less error prone way. A subset of feature is complete and sufficient and it is not a question of time when it becomes the full set what moderngl implements.

`moderngl` uses `glcontext` here:

https://github.com/moderngl/moderngl/blob/master/moderngl/src/ModernGL.cpp#L158-L167

on special platforms the existing function loading may not work. it should be somewhat straightforward to extend glcontext to support those cases.

**Comment by szabolcsdombi** [comment]
Here is a simple example for using glcontext and calling glViewport:

1. when no loader is provided zengl falls back to use glcontext

https://github.com/szabolcsdombi/zengl/blob/33c18d0ebc52e58b6e3a0755d29d11fa7ddd4a29/zengl.cpp#L643

2. the default loader is indeed returning a glcontext context

https://github.com/szabolcsdombi/zengl/blob/33c18d0ebc52e58b6e3a0755d29d11fa7ddd4a29/_zengl.py#L119

3. we populate a struct of gl function pointers

https://github.com/szabolcsdombi/zengl/blob/33c18d0ebc52e58b6e3a0755d29d11fa7ddd4a29/zengl.cpp#L651

4. the implementation loads every required function

https://github.com/szabolcsdombi/zengl/blob/33c18d0ebc52e58b6e3a0755d29d11fa7ddd4a29/zengl.hpp#L638

5. to load a method we invoke the loaders load method

https://github.com/szabolcsdombi/zengl/blob/33c18d0ebc52e58b6e3a0755d29d11fa7ddd4a29/zengl.hpp#L630

6. We use glViewport from C++

https://github.com/szabolcsdombi/zengl/blob/33c18d0ebc52e58b6e3a0755d29d11fa7ddd4a29/zengl.cpp#L1872

---

moderngl is doing exactly the same with a bit more logic around the context

**Comment by szabolcsdombi** [comment]
> Is there any example code showing how to use your glcontext package?

example provided above

> I am unsure how to extend ctx.load ('glViewport') shown in your test.py file.

you can modify the implementation to return some other C/C++ function for glViewport.

> How would I later invoke the glViewport () command?

example provided above (invoke is done from C++)

> Do I have to preload all the opengl commands?

No, actually this library is used by other libraries to do the function preloading.
This library provides the implementation for the gl* calls.
One can ask glcontext to return where is glViewport implemented.
