### ISSUE TITLE
error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'void (GLContext *)'

### ISSUE THREAD

**Issue by rayzchen** [moderngl/glcontext#27]
Cannot install via pip, this error happens:

```
    glcontext/x11.cpp:480:21: error: cannot initialize a member subobject of type 'void *' with an lvalue of type 'void (GLContext *)'
          {Py_tp_dealloc, GLContext_dealloc},
                          ^~~~~~~~~~~~~~~~~
```

**Comment by szabolcsdombi** [comment]
thank you for reporting this, please specify your platform.
for linux we have the `-fpermissive` flag that prevents this issue.

also adding a (void *) before all the c function types in the `_spec[]` lists resolves the problem.

**Comment by rayzchen** [comment]
I’m on Windows. To be honest, I’m not too willing to clone and edit the source code, I’m actually just using `pip install moderngl` and this happens.

**Comment by szabolcsdombi** [comment]
```
pip install -U pip wheel setuptools
pip install glcontext
```

for windows we have prebuild files (Python 3.7 ... Python 3.10) 
also windows should use the msvc compiler that does not really care about the error you pasted.
I fix this problem on Monday and I let you know how to install it if the release takes more time.

Do you have a Python install or Anaconda or anything else?

Please paste the output of

```
python --version
```

**Comment by szabolcsdombi** [comment]
actuually the fix was doable with the text editor at hand. please try to install from github directly:

```
pip install https://github.com/moderngl/glcontext/archive/refs/heads/master.zip
```

**Comment by naveen521kk** [comment]
> I’m on Windows. 

Why is `glcontext/x11.cpp` tried to compile in the first place? It's not for windows, on windows `glcontext/wgl.cpp` should be used instead.

**Comment by rayzchen** [comment]
My bad, I just realized I said Windows. Actually, I’m experimenting on Android (using Termux) which is technically Linux aarch64. That’s why `X11.cpp` was compiling.
