### ISSUE TITLE
error: cannot initialize a variable of type 'EGLDeviceEXT *' (aka 'void **') with an rvalue of type 'void *'

### ISSUE THREAD

**Issue by yurivict** [moderngl/glcontext#32]
```
glcontext/egl.cpp:219:23: error: cannot initialize a variable of type 'EGLDeviceEXT *' (aka 'void **') with an rvalue of type 'void *'
        EGLDeviceEXT* devices = malloc(sizeof(EGLDeviceEXT) * num_devices);
                      ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Version: 2.3.7
Python-3.9
clang-14
FreeBSD 13.1

**Comment by szabolcsdombi** [comment]
thank you for reporting this., if you make a PR for [glcontext](https://github.com/moderngl/glcontext) with `(EGLDeviceEXT *)` added before malloc we can merge it and release it.

**Comment by theoparis** [comment]
It seems like I have to install from git due to there being no release with https://github.com/moderngl/glcontext/commit/8a6918336869296565a0cb4a6c7c510f26443762 😕

**Comment by szabolcsdombi** [comment]
You can install directly from github.

`pip install https://github.com/moderngl/glcontext/archive/refs/heads/master.zip`

**Comment by szabolcsdombi** [comment]
Released https://github.com/moderngl/glcontext/releases/tag/2.4.0
