### ISSUE TITLE
Properly test darwin backend

### ISSUE THREAD

**Issue by einarf** [moderngl/glcontext#5]
There seems to be some instances of context creation fails on darwin. All i know is that it worked in moderngl 5.5.x and it doesn't using glcontext in 5.6. This needs to be investigated and fixed before we can release 5.6.

**Comment by cprogrammer1994** [comment]
can test with a really old hardware soon :)

both versions use the same code, they just access most of it a bit differently.

maybe 5.6 misses some initialization

**Comment by einarf** [comment]
I can test here as well. I just noticed if you specify glversion 4.0 in mgl 6 the context creation fails for some reason. I don't think that is the case in 5.5.x

**Comment by einarf** [comment]
Looks like `ctx->version_code` is not set when requesting version code 400 (darwin). It's an odd request, but it should probably still work because the user will get the highest available context on darwin anyway.

Trying to figure out what is going on..

**Comment by einarf** [comment]
This is a bug in pyglet

**Comment by einarf** [comment]
https://github.com/pyglet/pyglet/pull/108

**Comment by einarf** [comment]
https://github.com/pyglet/pyglet/pull/110
