### ISSUE TITLE
Need a way to pass in gl library

### ISSUE THREAD

**Issue by einarf** [moderngl/glcontext#6]
This is the case on linux at least. `libGL.so` vs `libGL.1.*` are the common it seems.

Maybe we should try those two alternatives if no glversion was passed in?

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/glcontext/blob/d53fdd38e6e2d267a3be98cdf637317d8033cbee/glcontext/x11.cpp#L82-L92

the internal implementation is flexible

the mini wrappers maybe omit using it, but it could be added, it was not yet decided how users should use this feature.

**Comment by einarf** [comment]
On all my linux boxes by default the available lib is `libGL.so.1`, not `libGL.so`. I see applications looking for both versions. I'm not sure what the correct default it. We probably want context creation on linux to be as painless as possible.

Do you have any insight about this?

**Comment by einarf** [comment]
For passing extra parameters there is work on moderngl side as well. We don't do anything there if a backend is passed in for example. Generally things are working pretty well as far as I can see (I have fixed most things already). It's mainly this remaining glue that is left for 5.6 + testing.

**Comment by einarf** [comment]
Fixed
